name: ci
on:
  push:
    branches: [ main ]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      PYTHON_VERSION: '3.11'
      IMAGE_V1: ghcr.io/${{ github.repository }}:v1
      IMAGE_SHA: ghcr.io/${{ github.repository }}:${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # ===== s3） =====
      # - name: Download model & lookups from S3 
      #   if: ${{ secrets.S3_MODEL_URI != '' }}
      #   env:
      #     AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION:            ${{ secrets.AWS_REGION || 'us-east-1' }}
      #     S3_MODEL_URI:          ${{ secrets.S3_MODEL_URI }}
      #     S3_ITEM_LOOKUP_URI:    ${{ secrets.S3_ITEM_LOOKUP_URI }}
      #     S3_STORE_LOOKUP_URI:   ${{ secrets.S3_STORE_LOOKUP_URI }}
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install awscli
      #     mkdir -p artifacts data/processed
      #     aws s3 cp "${S3_MODEL_URI}"        artifacts/model.joblib --region "${AWS_REGION}"
      #     aws s3 cp "${S3_ITEM_LOOKUP_URI}"  data/processed/item_lookup.parquet  --region "${AWS_REGION}"
      #     aws s3 cp "${S3_STORE_LOOKUP_URI}" data/processed/store_lookup.parquet --region "${AWS_REGION}"
      #     ls -lh artifacts || true
      #     ls -lh data/processed || true

      # =====  uvicorn → /healthz → /predict → /metrics =====
      - name: Install deps & smoke test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-serve.txt requests
          python -m tests.smoke_test

      # ===== GHCR =====
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: serve/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_V1 }}
            ${{ env.IMAGE_SHA }}
          provenance: false
