cat > .github/workflows/ci.yml <<'YAML'
name: ci
on:
  push: { branches: [ main ] }
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps & smoke test
        run: |
          python -m pip install --upgrade pip
          pip install -r serve/requirements-serve.txt requests
          python -m tests.smoke_test

      # ---- Optional: push Docker image to GHCR ----
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: serve/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:v1
            ghcr.io/${{ github.repository }}:${{ github.sha }}
YAML

